### ISSUE TITLE
Undefined array key "nbHits"

### ISSUE THREAD

**Issue by imlinfly** [shopwwi/webman-search#1]
[500] ErrorException in /vendor/shopwwi/webman-search/src/Adapter/MeiliSearch.php line 267
Undefined array key "nbHits"

从meilisearch查询返回的结果中并没有找到nbHits参数

![image](https://user-images.githubusercontent.com/45063822/192957640-e3b23c04-fd6f-4710-bc0f-8e47842d9719.png)
![image](https://user-images.githubusercontent.com/45063822/192957996-78ff1a9d-89e8-4c32-b9d7-e698fe7b47ab.png)

**Comment by phcent** [comment]
新版的meilisearch更改了返回字段 现已更正
