### ISSUE TITLE
这个插件 针对 elasticsearch 算是废了

### ISSUE THREAD

**Issue by ayhome** [shopwwi/webman-search#3]
可能作者是测试环境的问题，作者使用的  elasticsearch  最低版本应该是 8.0 ，这里没说清楚，
没有做用户认证，  折腾了一早上 去看了源码  一堆的bug，  
准备提取一些代码自己封装

**Comment by phcent** [comment]
是的 用的是elasticsearch高版本 可以直接调用官方源包的 每个人需求不同
